
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Amir Aref
# Username: arefa
#
# Assignment: A03
# Purpose: A pracitce to learn how to use functions effectively
# Google Doc Link: https://docs.google.com/document/d/1ADuZfF-wL0E9Xef3xzmLY6nyvgnU-8THRcrPKyY0h_o/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################
#
#wn.bgpic("")
#wn.setup(width=1200,height=1200)
#wn.bgpic("cartoon-land-5.gif")
#wn.addshape('cartoon-land-5.gif')
#wn.mainloop()




def function_1():
    """
This function is a series of code to draw a broken tv
    """
    pass

import turtle
rf = turtle.Turtle()
wn = turtle.Screen()

rf.begin_fill()
rf.color("#964B00")
rf.pensize(10)
rf.pendown()
rf.begin_fill()
rf.forward(100)
rf.right(45)
rf.forward(60)
rf.right(135)
rf.forward(185)
rf.right(135)
rf.forward(60)
rf.backward(60)
rf.end_fill()

rf.color("#000000")
rf.pensize(15)
rf.right(135)
rf.forward(100)
rf.left(90)
rf.forward(185)
rf.left(90)
rf.forward(100)
rf.left(90)
rf.forward(185)

rf.penup()
rf.backward(30)
rf.left(90)
rf.forward(14)
rf.color("#f9fb00")
rf.pendown()
rf.forward(70)
rf.penup()
rf.left(90)
rf.forward(15)
rf.pendown()
rf.color("#02feff")
rf.left(90)
rf.forward(70)
rf.penup()
rf.right(90)
rf.forward(15)
rf.pendown()
rf.color("#01ff00")
rf.right(90)
rf.forward(70)
rf.penup()
rf.left(90)
rf.forward(15)
rf.pendown()
rf.color("#fdbfbe")
rf.left(90)
rf.forward(70)
rf.penup()
rf.right(90)
rf.forward(15)
rf.color("red")
rf.pendown()
rf.right(90)
rf.forward(70)
rf.penup()
rf.left(90)
rf.forward(15)
rf.color("blue")
rf.pendown()
rf.left(90)
rf.forward(70)
rf.penup()
rf.right(90)
rf.forward(15)
rf.color("black")
rf.pendown()
rf.right(90)
rf.forward(70)
rf.penup()
rf.left(90)
rf.forward(15)
rf.pendown()
rf.color("white")
rf.left(90)
rf.forward(70)
rf.penup()
rf.right(90)
rf.forward(15)
rf.pendown()
rf.color("#02feff")
rf.right(90)
rf.forward(70)
rf.penup()
rf.left(90)
rf.forward(15)
rf.pendown()
rf.color("#01ff00")
rf.left(90)
rf.forward(70)
rf.penup()
rf.right(90)
rf.forward(15)


def function_2():
    """
This function is written to draw Turkey's Flag
    """
    pass

import turtle
wn = turtle.Screen()
me = turtle.Turtle()
me.penup()
me.goto(-100, 30)
me.pendown()
me.begin_fill()
for i in range(2):
    me.color("red")
    me.forward(120)
    me.left(90)
    me.forward(60)
    me.left(90)
me.end_fill()

me.begin_fill()
me.goto(-40, 60)
me.color("white")
for x in range(5):
    me.left(70)
    me.forward(4)
    me.right(140)
    me.forward(4)
me.end_fill()
me.penup()
me.begin_fill()
me.goto(-50, 50)
me.pensize(1)
me.pendown()
me.left(180)
for x in range(40):
    me.forward(1)
    me.right(5)
me.right(60)
me.forward(1)

me.left(270)
for x in range(30):
    me.forward(1)
    me.left(5)
me.end_fill()
me.penup()


me.right(10)
me.forward(1)
me.goto(15, 30)
me.pendown()
me.pensize(10)
me.right(30)
me.color("black")
me.forward(60)
me.left(90)
me.forward(70)

def main():
    """
    Docstring for main
    """
    # ...
    function_1()            # Function call to function_1
    function_2()            # Function call to function_2
wn.exitonclick()

main()

